### ISSUE TITLE
Can't download your plugin

### ISSUE THREAD

**Issue by glitchlover** [onlyafly/number-headings-obsidian#10]
![image](https://user-images.githubusercontent.com/59877631/130407133-d8747e7b-b576-4313-9916-edad0883a316.png)
What happened? here is the console log
![image](https://user-images.githubusercontent.com/59877631/130407345-a8a76a3c-7374-4a66-9781-4c9af21c28c0.png)

**Comment by gfidias** [comment]
Same here. Manually installed latest (v1.7.2). 
<img width="543" alt="Screenshot 2021-08-23 at 11 13 53" src="https://user-images.githubusercontent.com/23036873/130414040-e1bc8024-42d1-493d-9426-c0959c05248e.png">
Now, it cannot be updated to latest version 1.7.3 (?)
<img width="642" alt="Screenshot 2021-08-23 at 11 14 19" src="https://user-images.githubusercontent.com/23036873/130414061-0ef51aba-a556-4808-83ca-40d371219fcd.png">

**Comment by autonomygaps** [comment]
I'm also getting the "Failed to install" message.

**Comment by erex** [comment]
ditto on Windows machine from Obsidian 0.12.12

**Comment by onlyafly** [comment]
Hi  @erex @autonomygaps @glitchlover @gfidias : Sorry about that. The bug has been fixed in version 1.7.3
