### ISSUE TITLE
Erroneously removing Zettelkasten prefix

### ISSUE THREAD

**Issue by AtrusRiven** [onlyafly/number-headings-obsidian#12]
I have a problem with the plugin: I use Zettelkasten prefixes in first level headings, e.g. `202109161700 Heading title` (same as file name). When acitvating the plugin it removes the prefix completely if I choose not to number the first level (plugin settings). IMHO this is a bug. At the moment I unfortunately can’t use the plugin this way. Is there a possibility to fix that bug?

**Comment by onlyafly** [comment]
Let me see what I can do.
