### ISSUE TITLE
[Help Request] Using Headings "###"

### ISSUE THREAD

**Issue by FelipeRearden** [onlyafly/number-headings-obsidian#14]
Hello @onlyafly !!!!!

I'd like to ask your help with one specific workflow that I'm trying to implement with your amazing plug-in:

Here is my situation:

1- I have a note that only have level 3 headings `###` 

Here is my "raw" note:

![Screen Shot 2021-10-11 at 07 39 43](https://user-images.githubusercontent.com/85180696/136777069-e3820ed6-eee7-4134-83a9-2632bd5df1f8.png)

Here is the resut that I want to achieve:

![Screen Shot 2021-10-11 at 07 39 58](https://user-images.githubusercontent.com/85180696/136777101-073ed002-4e67-4234-9314-c6694710cfe2.png)

**As you can see, i just wanna apply `1` `2` and `3` with a level 3 headers.** :)

### I tried these settings to try to achieve this: 

**Attempt 1:**

![Screen Shot 2021-10-11 at 07 29 04](https://user-images.githubusercontent.com/85180696/136777213-770fe1ad-e53c-4292-a126-8f6e776274f6.png)
![Screen Shot 2021-10-11 at 07 29 43](https://user-images.githubusercontent.com/85180696/136777215-5f9e2932-c7bc-4608-8718-663f9c5f3930.png)

**Attempt 2:**

![Screen Shot 2021-10-11 at 07 30 36](https://user-images.githubusercontent.com/85180696/136777294-22d092c0-6189-433d-849e-3a1de5e13b1f.png)
![Screen Shot 2021-10-11 at 07 30 05](https://user-images.githubusercontent.com/85180696/136777296-0ac20aa3-f7ce-4c80-b715-33b26b5c79b2.png)

**Attempt 3:**

![Screen Shot 2021-10-11 at 07 32 08](https://user-images.githubusercontent.com/85180696/136777397-88d8ce78-ad21-49cc-bd64-4aa3b06f8491.png)
![Screen Shot 2021-10-11 at 07 32 46](https://user-images.githubusercontent.com/85180696/136777401-e8f21441-401b-48cd-9935-b86068b468b6.png)

**Here is my Settings Pane**
![Screen Shot 2021-10-11 at 07 36 12](https://user-images.githubusercontent.com/85180696/136777440-f44aaf92-8bf9-4217-ad49-8118e1e02494.png)

Could you help me to get the right setting to achieve this? :)

---

Thanks for your help!

Have a great day!!!

**Comment by onlyafly** [comment]
Forgot to close this back when I originally fixed it.
