### ISSUE TITLE
[Feature Request] New Command: `Number all Headings in the document using front matter settings`

### ISSUE THREAD

**Issue by FelipeRearden** [onlyafly/number-headings-obsidian#15]
Hello @onlyafly !!!!!

### My workflow

I have a note only with tweets that I regularly export from twitter to obsidian
- I use a Shortcut to export from iOS to Obsidian.

To make my note easy to search I have one header for each tweet:

![Screen Shot 2021-10-11 at 07 52 58](https://user-images.githubusercontent.com/85180696/136779649-e37a61c2-0d0b-460d-9a40-357196aca848.png)

After exportation I use your plug-in to create a numbered headings to my note

![Screen Shot 2021-10-11 at 07 51 35](https://user-images.githubusercontent.com/85180696/136779936-8cb1bdbf-b266-4ae6-99cc-b129e45bf8fd.png)

Since I import new tweets for this note everyday, I have to apply my front-matter settings `Number all Headings in the document` once a day to add new numbers to my list

![Screen Shot 2021-10-11 at 08 03 37](https://user-images.githubusercontent.com/85180696/136780060-8151b3fe-f2e9-421e-9c3f-66a653905ad2.png)

Every time I got this notification message when I use : `Number all Headings in the document`

![Screen Shot 2021-10-11 at 07 30 05](https://user-images.githubusercontent.com/85180696/136780099-40062b3c-5c9e-422c-858c-2b99855b5a0a.png)

### My Feature Request

I wanna request a new command to be used when you just need to update your note with the parameters previously defined in the front matter:

`Number all Headings in the document using front matter settings`

In my case, I already now my settings. I just want to update my note because of my new headers.

This way, I don't need to interact with the notification message box, I just need to apply the settings in the front-matter and continue to work :)

### Why I don't use `Automatic Numbering` ?

Since I have a lot of notes from books with huge TOC that uses `Humber Headings`, I don't want to automatic numbering everything in my vault. I don't want to have a service running in all my notes trying to look for an update. I rather two this manually
- I think Automatic Numbering is a great feature, but I rather do this manually :) 

---

Thanks for your help.

Have a great day

**Comment by ssmmtt** [comment]
skip the notification is a good idea and the best option for me. +1

**Comment by onlyafly** [comment]
Fixed in version 1.10.0
