### ISSUE TITLE
Not all the settings are transferred into frontmatter and are applied

### ISSUE THREAD

**Issue by mikkovedru** [onlyafly/number-headings-obsidian#19]
My settings:
![image](https://user-images.githubusercontent.com/2521942/139153983-04f661bb-3c27-409d-adbf-84d3df3b8e43.png)
What is being transferred to frontmatter:
![image](https://user-images.githubusercontent.com/2521942/139153950-842175c8-b468-4883-99f6-0087161a04e5.png)
![image](https://user-images.githubusercontent.com/2521942/139154134-f59e0cfa-ccd3-4176-9422-62c196fb5769.png)

## The verdict about the bug
The following settings are not being transferred:
- the first heading level. Always shows 1.
- separator style. Always a dot.
- ToC anchor. Always missing.

## System
- Linux Mint 20.2 Cinnamon
- Obsidian 0.12.19
- the latest plugin 1.8.0

**Comment by onlyafly** [comment]
@kassadin Thanks for the catch!
