### ISSUE TITLE
Highlight active header in Outline pane

### ISSUE THREAD

**Issue by DutchPete** [onlyafly/number-headings-obsidian#2]
Is it possible that, if I am in say header 4.1.3, that header is highlighted in the Outline pane?

**Comment by onlyafly** [comment]
Also interesting idea. I'll see what I can do.

**Comment by DutchPete** [comment]
Have you been able to have a look at this?

**Comment by DutchPete** [comment]
I have just installed the [*Dynamic toc*](https://github.com/aidurber/obsidian-plugin-dynamic-toc) plug-in with which you can created a ToC at the top of the note - useful when the note is exported.

However, that ToC now has duplicate numbers because your plug-in adds numbers to the headings.

![image](https://user-images.githubusercontent.com/10794265/131222603-036c1165-6dce-46f5-830b-81e9e7507aed.png)

I like your plug-in because the numbers it creates are also shown in the Outline pane.

So, I am not sure whose issue this: the *Dynamic toc* plug-in's the *number headings* plug-in's. But since you are considering an alternative outline pane feature I was wondering if somehow the 2 could be combined or merged to allow both features.

**Comment by onlyafly** [comment]
@DutchPete It seems like there's a lot of duplication in Obsidian plugins :)

I just finished implementing this feature as well as part of this plugin. I'm still testing to make sure it works in every case, but you can try it out here: https://github.com/onlyafly/number-headings-obsidian/tree/toc

**Comment by DutchPete** [comment]
@onlyafly I installed version 1.8.0 but it “Failed to load”.
I looked at the files on the folder and noticed `main.js` is missing. I load `main.js` of version 1.7.3, and sure enough the plug-in loaded, but after refreshing Obs nothing showed.

In the subfolder, `src` I noticed a `main.ts`, copied that to the parent folder and renamed it to `main.js` after taking out the old one, but again the plug-in failed to load.

**Comment by onlyafly** [comment]
@DutchPete Ah, yes. Fixed now.

**Comment by DutchPete** [comment]
@onlyafly Yes, version 1.8.0 now loads without any problems, but ………

- it does not show a highlight in the Outline pane, and
- the numbering does not work.

So, I put 1.7.3 back.

**Comment by Aidurber** [comment]
Hi @onlyafly, I'm the creator of Dynamic ToC. I think @DutchPete's issue can be resolved with CSS as I've mentioned [here](https://github.com/Aidurber/obsidian-plugin-dynamic-toc/issues/3#issuecomment-917609566).

The alternative to CSS would be number-headings-obsidian gets re-architected to use a markdown post-processor with a higher `sortOrder` so it runs after the Dynamic ToC. But that sounds like a lot of work and would fundamentally change how your plugin has to work. This doesn't sound fair or worthwhile for you. 

Here is what it looks like with the CSS I've suggested @DutchPete uses. 
![image](https://user-images.githubusercontent.com/5732291/132984469-9f91212a-18b2-4d1d-ab8f-92e04892cf67.png)

**Comment by DutchPete** [comment]
@onlyafly The number duplication is actually another issue is now solved with a very simple piece of CSS code - see [**here**](https://github.com/Aidurber/obsidian-plugin-dynamic-toc/issues/3#issuecomment-917614473).

That still leaves the original topic of this issue *
Highlight active header in Outline pane*.

**Comment by onlyafly** [comment]
Thanks, I'll look into this on my side!

**Comment by DutchPete** [comment]
Kevin, no news yet I guess?

**Comment by onlyafly** [comment]
I can't find a way to do this without changing the basic idea behind the plugin :(

**Comment by DutchPete** [comment]
OK, fair enough.
