### ISSUE TITLE
Numbers not part of the note

### ISSUE THREAD

**Issue by DutchPete** [onlyafly/number-headings-obsidian#21]
When I have a note with headers, then your plug-in adds numbers to those headers. Numbered headers are useful for navigation in long notes.

However, when e.g. a new header is inserted, the numbers in that note change, and all the links to those headers break.

Typora provides virtual heading numbering with some CSS code, and the numbering is NOT part of the note. Now, I asked about this a long time ago and someone (cannot remember who) explained that Typora and Obsidian have a different way of handling ………… uhm, something, so what Typora does is not possible in Obsidian. But with JavaScript a lot more is possible.

Is there a way for your plug-in to provide numbers as virtual numbers, i.e. not make them part of the note?

**Comment by DutchPete** [comment]
If you look at [**this**](https://github.com/mgmeyers/obsidian-embedded-note-titles/) plug-in, you'll see that *"This plugin does not modify notes, and the title is not a part of the document itself."*

**Comment by onlyafly** [comment]
It is an interesting idea, but it sounds like an idea for a different plugin. When I created this plugin, I wanted something that modifies the document directly.

**Comment by DutchPete** [comment]
> When I created this plugin, I wanted something that modifies the document directly.

With Typora one has to add a snippet to achieve virtual numbers, while Zettlr provides it out of the box.

Is there no way to amend your plug-in? For example, could numbering virtual or as part of the note be made togglable?
