### ISSUE TITLE
Skip headers for numbering

### ISSUE THREAD

**Issue by Zeta611** [onlyafly/number-headings-obsidian#25]
Thank you for providing such a useful plugin.

I occasionally found a need to skip some header from being numbered.
For instance, I want to prevent the `## Contents ^toc` from counted.

More generally, a command to prevent sections with custom suffix, e.g., `# Uncounted ^exclude`, to skip them would be useful.

FYI, LaTeX provides starred commands like `\section*` for such usage.

**Comment by onlyafly** [comment]
Cool idea. I'll consider this.

**Comment by piotrnajda3000** [comment]
Would love to see it!

**Comment by wedgen** [comment]
I second that.  I have been converting from VScode to Obsidian for my notes app and this has been something from getting me to parity.

**Comment by faurehu** [comment]
I came to this issues board looking for a way to do this, thank you for creating this issue so that I know this is not yet implemented.

**Comment by gitAlwin** [comment]
Yes! I would also like this feature! Thank you for creating this plugin, I ❤️ it!

**Comment by onlyafly** [comment]
Alright, you guys convinced me :) Added this feature in the newest version, 1.16.0, which should be available later today.

**Comment by robkisk** [comment]
thanks for adding this. is there an example for how to use this to skip top level heading?
