### ISSUE TITLE
FR: Option to choose which letter/number to start numbering from

### ISSUE THREAD

**Issue by SkepticMystic** [onlyafly/number-headings-obsidian#27]
Hey, awesome plugin you've got here :D

One issue I've come accross is that in some situations, I want the numbering for a level 1 heading to start from a value different from `1`.

For example, using the Longform Writing plugin, the sections of my thesis are split into different notes. So for chapter 2, for example, I want the numbering to start at `2`, `2.1`, etc. instead of `1` as is the default.

**Comment by onlyafly** [comment]
Fixed in version 1.11.0, releasing later today! See #33 also
