### ISSUE TITLE
Mannully set the number of the first level heading, and automatically  number other headings accordingly

### ISSUE THREAD

**Issue by hqgu** [onlyafly/number-headings-obsidian#33]
Is it possible to manually set the number of the first level heading, and automatically number other headings accordingly?

For example,  I have a document, which is the Third Chapter of a book. Therefore, I'd like to set the first-level heading (which is the Chapter title) to 3, and then the later level 2 heading could be automatically numbered as 3.1,  3.2, ..., and so on. 

# 3 Chapter Title

**Comment by onlyafly** [comment]
Not currently, but I'll look into it!

**Comment by hqgu** [comment]
Thank you. Or it can simplely provide a option to set the starting number for the first level heading.

**Comment by hqgu** [comment]
Any updation on this feature?

**Comment by onlyafly** [comment]
Fixed in 1.11.0, releasing later today.
