### ISSUE TITLE
I have some problem with internal link.

### ISSUE THREAD

**Issue by WystanW** [onlyafly/number-headings-obsidian#35]
I have an internal link [[#my_heading]]. If I number all headings in a document, "my_heading" will turn to "1 my_heading". Then the internal link will not work. Is there any way to show the head number just in preview mode not in the editor mode?

**Comment by superzjt526** [comment]
+1

**Comment by DimeSaga** [comment]
I use css to implement it in typora, obsidian should also work, but I don't know how to do it. This is an idea

**Comment by onlyafly** [comment]
Yeah, internal links are an issue with the plugin.

However, this is a fundamental design decision of this plugin, to edit the text, not just the display, so unlikely there is a fix. However, I'm looking into if it is possible to update the internal links as well.
