### ISSUE TITLE
Separator Style Bug with Whitespace

### ISSUE THREAD

**Issue by yixin0829** [onlyafly/number-headings-obsidian#36]
Hi!!

First of all just to want to say a big THANK YOU for developing this plugin! It really helped me a lot and I love it so much.

One small minor bug: in the setting => `Separator Style`, I found when you add a space before your separator like ` -` instead of doing `-`, the auto numbering will keep adding separators.

See screenshot:
![image](https://user-images.githubusercontent.com/56566212/188287030-7658be56-c08b-45dd-b4f1-7fb8d7083a8a.png)

To reproduce the bug shown above:
1. Go on Obsidian and create a new note
2. Turn on auto numbering and set `Separator style` to ` -` (i.e. whitespace + dash)
3. Add some headings

It might be worth to fix (not a priority). I personally find that using ` -` (whitespace + dash) as separator makes things easier to read than using `-` only (e.g. `1.2 - My heading`  vs. `1.2- My heading`)

**Comment by Lotus49b** [comment]
I'm experiencing this problem too.

Any updates on this?

**Comment by onlyafly** [comment]
Fixed in version 1.10.1

**Comment by onlyafly** [comment]
@yixin0829 and @Lotus49b : I hope this fix solved your problem!

**Comment by yixin0829** [comment]
Tested and solved the issue. @onlyafly  Thanks Kevin!
