### ISSUE TITLE
"Table of Contents Anchor" causes Obsidian to get stuck

### ISSUE THREAD

**Issue by DEabcdp** [onlyafly/number-headings-obsidian#37]
If there are no other headings under the heading "^toc", Obsidian will get stuck after one second and no clicking, typing or other arbitrary actions will be possible. You can only force close Obsidian and delete "^toc" immediately within one second of opening to avoid the next stuck.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/62452364/189281794-75029eba-829a-44e6-805a-a51ae65ab2da.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/62452364/189282129-3674590f-34be-4ef2-9993-d0a769448eb7.png">

**Comment by onlyafly** [comment]
Thanks for submitting this! I fixed this bug in the upcoming version 1.11.0, which I will release later today.
