### ISSUE TITLE
I cannot update or reinstall to 1.10.2 (and there is no 1.11.0)

### ISSUE THREAD

**Issue by merlinuwe** [onlyafly/number-headings-obsidian#39]
Thanks for your great plugin.

I saw your update, upgraded and got an error message. So I deinstalled your plugin to install it from scratch. Now:

![image](https://user-images.githubusercontent.com/4138869/210170360-d61b3e7c-b88a-4eaa-92ca-d45ba09e24ca.png)

There is no 1.11.0

![image](https://user-images.githubusercontent.com/4138869/210170477-c0c7baff-3f8b-485c-8eca-8fb37697ad9f.png)

**Comment by onlyafly** [comment]
@merlinuwe You were just a little too fast :) I just released 1.11.0 5 minutes ago :)

Should work now!

**Comment by merlinuwe** [comment]
Thank you, but I get again

![image](https://user-images.githubusercontent.com/4138869/210178193-45239dcf-5b30-478e-b6b3-1c7b34709abe.png)
