### ISSUE TITLE
Double trouble ... with 2 toc instead of 1

### ISSUE THREAD

**Issue by merlinuwe** [onlyafly/number-headings-obsidian#41]
Any idea why the table of contents doubles?

![image](https://user-images.githubusercontent.com/4138869/215281888-bb587974-ed64-44df-810a-40c98b09c890.png)

These are my settings:

![image](https://user-images.githubusercontent.com/4138869/215281907-a8e5bfde-d195-4e83-b763-a7c8ec0282ea.png)

Here is the complete file content:

---
aliases: [Icons]
tags: [Icon, Folder, File]
Dateiname: Plugin supercharged links.md
filename: Plugin supercharged links
filenamemd: IT Grundlagen/MD Anleitungen/Obsidian Tricks/Obsidian plugins/supercharged links/Plugin supercharged links.md
filenamemd2: P:\Obsidian/IT Grundlagen/MD Anleitungen/Obsidian Tricks/Obsidian plugins/supercharged links/Plugin supercharged links.md
template: [TEMPLATE Neue Notiz]
number headings: first-level 2, max 6, 1.1, auto, contents ^toc
erstellt: Samstag, 28. Januar 2023, 18:20:33 Uhr
geändert: Samstag, 28. Januar 2023, 18:29:13 Uhr
---

# Plugin supercharged links

Links

- [[#Plugin supercharged links|Plugin supercharged links]]
- [[#Inhaltsverzeichnis ^toc|Inhaltsverzeichnis]]
	- [[#1 Einstellungen|1 Einstellungen]]

# Inhaltsverzeichnis ^toc

- [[#Plugin supercharged links|Plugin supercharged links]]
- [[#Inhaltsverzeichnis ^toc|Inhaltsverzeichnis]]
	- [[#1 Einstellungen|1 Einstellungen]]

## 1 Einstellungen

![[2023-01-28-superchared-links-settings.png|900]]

**Comment by merlinuwe** [comment]
Thank you for trying.
When I delete the line `number headings: first-level 2, max 6, 1.1, auto, contents ^toc` from yaml, the table of contents appears only once.
Do you have any idea, what I can do to narrow down the isue? I suspect the problem has something to do with my other plugins.

SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.2
	Snippets enabled: 22
	Restricted mode: off
	Plugins installed: 71
	Plugins enabled: 40
		1: Buttons v0.4.19
		2: Commander v0.4.9
		3: Completr v3.1.3
		4: Contextual Typography v2.2.4
		5: Copy document as HTML v0.4.0
		6: Dataview v0.5.55
		7: Dictionary v2.22.0
		8: Editor Syntax Highlight v0.1.3
		9: Execute Code v1.7.1
		10: Excel to Markdown Table v0.4.0
		11: File Explorer Note Count v1.2.0
		12: GPT-3 Notes v0.2.6
		13: Janitor v1.0.7
		14: Linter v1.10.3
		15: Number Headings v1.13.0
		16: Paste image rename v1.6.1
		17: Show Current File Path v0.5.2
		18: Style Settings v1.0.3
		19: Symbols Prettifier v1.1.1
		20: Templater v1.16.0
		21: Vault Statistics v0.1.3
		22: Minimal Theme Settings v6.3.1
		23: Pandoc Plugin v0.4.1
		24: Icon Folder v1.7.0
		25: Hover Editor v0.11.9
		26: Media Extended v2.11.1
		27: Text Generator v0.2.21
		28: Editing Toolbar v2.3.1
		29: Omnisearch v1.13.0
		30: Recent Files v1.3.5
		31: Remember cursor position v1.0.7
		32: Chronology v1.1.4
		33: Text Extractor v0.4.3
		34: Supercharged Links v0.9.3
		35: Obsidian Enhancing Export v1.1.10
		36: Bulk Rename v0.5.2
		37: Export Image plugin v1.0.3
		38: Obsidian Camera v1.5.0
		39: Auto Glossary v0.9.0
		40: ChatGPT MD v1.1.1

**Comment by onlyafly** [comment]
Sorry for the long delay. Just came back to this, and I am still unable to reproduce it.
