### ISSUE TITLE
Incorrect numbering for nested headings when top-level heading is unnumbered 

### ISSUE THREAD

**Issue by InvisOn** [onlyafly/number-headings-obsidian#48]
# Problem Description

I am unsure whether this is intended behaviour or a bug. I would like the top level not to be numbered but to have the lower level headings be numbered as if the top level heading was numbered.

# Expectations

```
# heading 1

## 1.1 Contents ^toc

- [[#heading 1|heading 1]]
	- [[#1.1 Contents ^toc|1.1 Contents]]
- [[#heading 2|heading 2]]
	- [[#2.1 sub 1|2.1 sub 1]]
		- [[#2.1.1 sub 2|2.1.1 sub 2]]

# heading 2

## 2.1. sub 1

### 2.1.1. sub 2
```
# Actual Result

```
# heading 1

## 1. Contents ^toc

- [[#heading 1|heading 1]]
	- [[#1. Contents ^toc|1. Contents]]
- [[#heading 2|heading 2]]
	- [[#1. sub 1|1. sub 1]]
		- [[#1.1. sub 2|1.1. sub 2]]

# heading 2

## 1. sub 1

### 1.1. sub 2
```

# Settings Used

- No frontmatter was set

![image](https://user-images.githubusercontent.com/17982633/230805681-dbf2c8e9-2d61-4bd4-b95c-37fbb14a86c0.png)

# Other settings I tried to get the desired result

- Combinations of,

![image](https://user-images.githubusercontent.com/17982633/230806774-532b24ee-2a37-4084-8694-aef1dcf12ce3.png)

And

![image](https://user-images.githubusercontent.com/17982633/230806930-7496f1e2-3ac2-40dd-b8f1-50b5b5d11aaf.png)

# Version Information

- OS: Pop!_OS 22.04 LTS x86_64
- Obsidian version: v1.1.16
- Plugin version: 1.13.0

**Comment by onlyafly** [comment]
This is solvable by using the "first-level 2" setting.

For example, use this in the front matter:

`number headings: auto, first-level 2`
