### ISSUE TITLE
auto skip the first head number when there is no first head

### ISSUE THREAD

**Issue by xiligey** [onlyafly/number-headings-obsidian#50]
My markdown code:
```
## head2
### head3
#### head4
##### head5
```
result after processing of this plugin:

![image](https://github.com/onlyafly/number-headings-obsidian/assets/72738024/94065c61-46a5-4cdf-b640-b804a484cd80)

Can we drop this "0." ? Because I don't have the first head but it shows zero.

**Comment by merlinuwe** [comment]
Me too. ;-)

**Comment by onlyafly** [comment]
You can solve this using the "first-level 2" setting.

For example, you could put this in the front matter:

`number headings: first-level 2, auto`
