### ISSUE TITLE
When headings are re-numbered (and therefore re-named), Links to them are broken.

### ISSUE THREAD

**Issue by fluidstu** [onlyafly/number-headings-obsidian#52]

**Comment by Helmoes** [comment]
I also have this issue. Could an action be implemented to fix broken links?

**Comment by achille-martin** [comment]
Indeed, if you rename the header and then re-generate the numbered headings, the ToC still displays the old header name.

The renaming of the header can be applied by removing the `#` and then reapplying them.
Then, after applying the numbering again, the ToC displays the right name.

The workaround is probably not the way to go, but it works until a fix is applied.

**Comment by jssegre** [comment]
Love the plugin, but this is unfortunately a major sticking point as currently being vigilant and using find & replace in vscode is the only way to prevent links across large vaults from breaking :(

**Comment by onlyafly** [comment]
Duplicate of #26
