### ISSUE TITLE
How can I change the formatting?

### ISSUE THREAD

**Issue by bibek-maharjan** [onlyafly/number-headings-obsidian#8]
![image](https://user-images.githubusercontent.com/76084262/128956022-1cf0b104-1185-421f-859e-191334d22e77.png)

How can I make it render like "1. " or "1 - "?

**Comment by onlyafly** [comment]
Hi @bibek-maharjan It is not currently possible, but I'm going to look into it.

**Comment by onlyafly** [comment]
Hi @bibek-maharjan: I've added the support like you requested. Try it out!
