### ISSUE TITLE
Plug-in obstructs Cmd+Z (undo)

### ISSUE THREAD

**Issue by DutchPete** [onlyafly/number-headings-obsidian#9]
I am on a Mac and have noticed that when the plug-in is enabled I am not longer able to do Cmd+Z (undo), a keyboard shortcut that I use frequently.

What happens is that when it is enabled I can make 3 keystrokes, e.g. `aaa`, and Cmd+Z will undo all 3 in 1 go.

If I do `aaaa` Cmd+Z does not undo anything, and instead jumps to a different location on the page. When I scroll back to where I came from, sure enough `aaaa` is still there.

**Comment by onlyafly** [comment]
Hi @DutchPete: Are you using version 1.6.1? I made some fixes that should solve that problem in that version. Let me know if that doesn't solve the problem.

**Comment by DutchPete** [comment]
I was using 1.4.2. Today I noticed the latest release is 1.6.1, which I installed and the bug is gone !! Many thanks for the fix 👍

**Comment by onlyafly** [comment]
Great to hear!
